### ISSUE TITLE
hardcode checks for g++ c++ and i++

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/supybot-fedora#30]
so we don't award badges to them.. ;)

**Comment by bitlord** [comment]
I'm not sure do we need to exclude **'g'**, **'c'** and **'i'** as lowercase only or both?
I did a small test script, which looks ok to me, this is the code https://github.com/bitlord/supybot-fedora/commit/cc3f8d4a4cd294f1becc7f3ebdec03f1c6a288fd

**Comment by bitlord** [comment]
Also, do you think two **if**s is too much, I can combine it into one I guess?
`...
 if len(recip) == 1 and recip.capitalize() in ['C','G','I']:
...`

**Comment by ralphbean** [comment]
I think this is good now and fixed with #36.
