### ISSUE TITLE
karma zodbot reply should not show cookie badge url

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/supybot-fedora#33]
I don't see any benefit in showing url's like https://badges.fedoraproject.org/badge/macaron-cookie-i.
e.g. See we have https://badges.fedoraproject.org/badge/chocolate-chip-cookie-ii badge but still zodbot showed me today this message
<zodbot> paragan: Karma for puiterwijk changed to 14:  https://badges.fedoraproject.org/badge/macaron-cookie-i

So, either show related karma level url or don't show it.

**Comment by ralphbean** [comment]
Let's show this url instead:  https://badges.fedoraproject.org/tags/cookie/any

This is just a config value, too, so it doesn't require any code change.

**Comment by ralphbean** [comment]
Done.
