### ISSUE TITLE
RFE: .nextelection command

### ISSUE THREAD

**Issue by decause** [fedora-infra/supybot-fedora#35]
It would be great to be able to type <code> .nextelection</code> to zodbot, and have it post the next election date, with a link to the elections page.

@ralphbean approved :+1:

**Comment by pypingou** [comment]
Retrieving the info from where ? Elections or fedocal or ?

**Comment by ralphbean** [comment]
@decause suggested to me that the data was already in fedocal.

**Comment by pypingou** [comment]
If it is not already we could/should add it there, but cool it means I don't have to add an API to elections :-D

**Comment by ryanlerch** [comment]
Going to close this one off.

Please reopen if you really want this implemented.
