### ISSUE TITLE
RFE: team name suggestion?

### ISSUE THREAD

**Issue by mairin** [fedora-infra/supybot-fedora#75]
I don't know how this would work - would likely need some kind of integration with meetbot itself - but it would be nice if when you're starting your meeting, that you could ask meetbot for a list of suggested team names based on m0te's team listing. e.g. the command could be something like:

> #prepmeeting 

'Hi, here are meetings I know about you could use for #startmeeting: magazine, design-team, hubs, ...'

**Comment by cverna** [comment]
Done :+1:

**Comment by ryanlerch** [comment]
WE run our own fork of meetbot that zodbot uses -- if this is a feature request that you still want -- please file it over there

https://github.com/fedora-infra/supybot-meetbot
